name: abitplay
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.1
  http_parser: ^4.0.0
  awesome_dialog: ^2.0.0
  cached_network_image: ^2.2.0+1
  carousel_slider: ^2.3.1
  http: ^0.13.0
  timer_builder: ^2.0.0
  flutter_paginator:
    path: flutter_paginator-0.0.6_atht/
  introduction_screen:
    path: introduction_screen-1.0.9_atht/
  shared_preferences: ^2.0.8
  persistent_bottom_nav_bar: ^3.2.0
  youtube_player_flutter: ^8.0.0
  share: ^0.6.5+4
#  flutter_paginator: ^0.0.6
  video_player: ^2.1.1
  firebase_analytics: ^5.0.11
  country_pickers: ^2.0.0
  email_validator: '^1.0.0'
  flutter_statusbarcolor: ^0.2.3
  html: ^0.14.0+4
  flutter_html:
  connectivity: ^2.0.2
  fluttertoast: ^7.1.6
  intl: ^0.16.0
  search_page: ^1.3.0
  audioplayers: ^0.20.1
  flutter_webview_plugin: ^0.4.0
  url_launcher: ^6.0.3
  passcode_screen: ^2.0.0
  onesignal_flutter: ^3.2.3
  app_settings: ^4.1.0
  local_auth:
    path: local_auth-1.1.5_atht/


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/
    - assets/videos/
    - assets/icons/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600

    - family: DMSans
      fonts:
        - asset: assets/fonts/DMSans-Regular.ttf

    - family: WorkSansSemiBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-SemiBold.ttf

    - family: WorkSansBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Bold.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
        - asset: assets/fonts/Montserrat-Light.ttf
        - asset: assets/fonts/Montserrat-Medium.ttf

    - family: WorkSansMedium
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Medium.ttf
    - family:  MyFlutterApp
      fonts:
        - asset: assets/fonts/MyFlutterApp.ttf